stages:
  - deploy



deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster local --server="${SERVER}"
    - kubectl config set clusters.local.certificate-authority-data "${CERTIFICATE_AUTHORITY_DATA}" --set-raw-bytes=false
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=local --user=gitlab
    - kubectl config use-context default
    - kubectl delete namespace the-project
    - kubectl create namespace the-project
    - kubectl apply -f 110-bootnode-service.yml
    - kubectl apply -f 120-bootnode-deployment.yml
    - kubectl apply -f 130-bootnode-registrar-service.yml
    - kubectl apply -f 140-bootnode-registrar-deployment.yml
    - kubectl apply -f 210-ethstats-service.yml
    - kubectl apply -f 220-ethstats-secret.yml
    - kubectl apply -f 230-ethstats-deployment.yml
    - kubectl apply -f 240-ethstats-ingress.yml
    - kubectl apply -f 310-geth-configmap.yml
    - kubectl apply -f 320-geth-miner-secret.yml
    - kubectl apply -f 330-geth-miner-deployment.yml
    - kubectl apply -f 410-geth-tx-service.yml
    - kubectl apply -f 420-geth-tx-deployment.yml
