apiVersion: v1
kind: Secret
metadata:
  name: eth-geth-miner
  namespace: the-project
  labels:
    app: eth-geth-miner
type: Opaque
data:
  # echo -n 'password' | base64
  accountsecret: "cGFzc3dvcmQ="
